//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.08 at 06:16:56 PM CEST 
//


package it.minux.increase.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.minux.increase.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.minux.increase.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoverageRequests }
     * 
     */
    public CoverageRequests createCoverageRequests() {
        return new CoverageRequests();
    }

    /**
     * Create an instance of {@link CoverageRequestType }
     * 
     */
    public CoverageRequestType createCoverageRequestType() {
        return new CoverageRequestType();
    }

    /**
     * Create an instance of {@link InstallationFailures }
     * 
     */
    public InstallationFailures createInstallationFailures() {
        return new InstallationFailures();
    }

    /**
     * Create an instance of {@link InstallationFailureType }
     * 
     */
    public InstallationFailureType createInstallationFailureType() {
        return new InstallationFailureType();
    }

    /**
     * Create an instance of {@link SupportRequests }
     * 
     */
    public SupportRequests createSupportRequests() {
        return new SupportRequests();
    }

    /**
     * Create an instance of {@link SupportRequestType }
     * 
     */
    public SupportRequestType createSupportRequestType() {
        return new SupportRequestType();
    }

    /**
     * Create an instance of {@link Towers }
     * 
     */
    public Towers createTowers() {
        return new Towers();
    }

    /**
     * Create an instance of {@link TowerType }
     * 
     */
    public TowerType createTowerType() {
        return new TowerType();
    }

    /**
     * Create an instance of {@link Topology }
     * 
     */
    public Topology createTopology() {
        return new Topology();
    }

    /**
     * Create an instance of {@link TowerDetailsType }
     * 
     */
    public TowerDetailsType createTowerDetailsType() {
        return new TowerDetailsType();
    }

    /**
     * Create an instance of {@link UsersLocations }
     * 
     */
    public UsersLocations createUsersLocations() {
        return new UsersLocations();
    }

    /**
     * Create an instance of {@link UserLocationType }
     * 
     */
    public UserLocationType createUserLocationType() {
        return new UserLocationType();
    }

    /**
     * Create an instance of {@link PointEventType }
     * 
     */
    public PointEventType createPointEventType() {
        return new PointEventType();
    }

    /**
     * Create an instance of {@link PanelType }
     * 
     */
    public PanelType createPanelType() {
        return new PanelType();
    }

}
